### ISSUE TITLE
Defining the .env strings

### ISSUE THREAD

**Issue by adriatic** [auth0-samples/auth0-pnp-abc-timesheets#3]
I am having difficulty to understand how is is **[this section](https://github.com/auth0-samples/auth0-pnp-abc-timesheets/blob/master/timesheets-api/node/README.md#set-the-configuration-values)** to be interpreted

- `{DOMAIN}`: Set this to the value of your Auth0 Domain. You can retrieve it from the *Settings* of your Client at the [Auth0 Dashboard](https://manage.auth0.com/#/clients).
- `{API_IDENTIFIER}`: Set this to the value of your API Identifier. You can retrieve it from the *Settings* of your API at the [Auth0 Dashboard](https://manage.auth0.com/#/apis).

My domain is `aureliatools.auth0.com` - do I define the respected line in the **`.env`** file as 

1. `AUTH0_DOMAIN={aureliatools.auth0.com}`
or
2. `AUTH0_DOMAIN=aureliatools.auth0.com`

I would think the case 2. applies as the curly braces without the `$` make no sense in this context. They seem to be used as a "visual delineation" for the human reader - and that I do find confusing (not only in this article - it appears everywhere.

_Note: this might be perceived as nit-picking, but by now, you know me better - I strive for clarity, effort which includes confusion avoidance 😄_

**Comment by adriatic** [comment]
### Big 👍 for this whole app and related **[tutorial](https://auth0.com/docs/architecture-scenarios/application/spa-api)**; it feels as if you created it just for me.

**Comment by jerriep** [comment]
It should be `AUTH0_DOMAIN=aureliatools.auth0.com`

The curly braces are used when samples are downloaded through the Auth0 documentation website to identify variables which we can replace with actual values from your Auth0 configuration. This is not actually enabled for these samples, but may in the future. This is consistent with the way the Auth0 quickstarts work as well.

**Comment by adriatic** [comment]
Thank you for explaining this.
