### ISSUE TITLE
Code - README mismatch in 

### ISSUE THREAD

**Issue by adriatic** [auth0-samples/auth0-pnp-abc-timesheets#5]
The section **[Angular Single Page Application](https://github.com/auth0-samples/auth0-pnp-abc-timesheets/blob/master/timesheets-spa/angular/README.md#angular-single-page-application)** states

## Set the configuration values

Rename the `auth0-variables.ts.example` file in the `src/app/auth` folder to `auth0-variables.ts` Once you have renamed the file you should set the following values in your new `auth0-variables.ts` file:

- `{DOMAIN}`: Set this to the value of your Auth0 Domain. You can retrieve it from the *Settings* of your Client at the [Auth0 Dashboard](https://manage.auth0.com/#/clients).
- `{CLIENT_ID}`: Set this to the value for your Auth0 Client. You can retrieve it from the *Settings* of your Client at the [Auth0 Dashboard](https://manage.auth0.com/#/clients).
- `{API_IDENTIFIER}`: Set this to the value of your API Identifier. You can retrieve it from the *Settings* of your API at the [Auth0 Dashboard](https://manage.auth0.com/#/apis).

This does not describe the content of the **[auth0-variables.ts.example](https://github.com/auth0-samples/auth0-pnp-abc-timesheets/blob/master/timesheets-spa/angular/src/app/auth/auth0-variables.ts.example)** file being
```
interface AuthConfig {
  clientID: string;
  domain: string;
  callbackURL: string;
  apiUrl: string;
}

export const AUTH_CONFIG: AuthConfig = {
  clientID: '{CLIENT_ID}',
  domain: '{DOMAIN}',
  callbackURL: 'http://localhost:4200/callback',
  apiUrl: '{API_IDENTIFIER}'
};
```

I suggest to point out that the `apiUrl` is the entity named `Identifier` on the https://manage.auth0.com/#/apis/59499d370be1012a0db4f4c8/settings, which I defined as **`https://api.aureliatools.com/timesheets`** (this is of course specific to my instance of this app).

___All this writing to indicate how it would be helpful to associate the string `apiURL` in `auth0-variables.ts` file with the string `Identifier` on the Auth0 APIs page.___

**Comment by adriatic** [comment]
### Added later:

Note also that the [README.md](https://github.com/auth0-samples/auth0-pnp-abc-timesheets/blob/master/timesheets-spa/angular/README.md) does not mention anything about **`callbackUrl `** and its value, while the same is needed in the [auth0-variables.ts.example](file)

**Comment by jerriep** [comment]
I renamed the `apiUrl` variable to `audience`. This should make things more clear. The `apiUrl` now refers to the actual URL for the API.

This README is not supposed to go into too much detail. Please read https://auth0.com/docs/architecture-scenarios/application/spa-api for full details

**Comment by adriatic** [comment]
Again, thank you for your clarifications and allow me a few comments as well.

> This README is not supposed to go into too much detail. Please read https://auth0.com/docs/architecture-scenarios/application/spa-api for full details

I am well aware of the https://auth0.com/docs/architecture-scenarios/application/spa-api document; it is one of the best documents on Auth0 website and because I liked it so much, I decided to add it to my collection of samples that I am creating for Aurelia Community. My comments on the matching README were written with the understanding that `This README is not supposed to go into too much detail` - I only wanted to point out the inconsistencies between the architecture scenario document and the README. It seems that you took my intentions incorrectly 😄
