### ISSUE TITLE
timesheets-spa application fails to compile

### ISSUE THREAD

**Issue by adriatic** [auth0-samples/auth0-pnp-abc-timesheets#6]
Here is the error message I get when running **`npm start`** command in the **[angular](https://github.com/auth0-samples/auth0-pnp-abc-timesheets/tree/master/timesheets-spa/angular)** folder

```
                                                                                                                        
ERROR in H:/work/aurelia-auth0/auth0-pnp-abc-timesheets/timesheets spa/angular/src/app/auth/auth.service.ts (102,32): Property 'silentCallbackURL' does not exist on type 'AuthConfig'.                                                         
```

Clearly the file **[`auth0-variables.ts.example`](https://github.com/auth0-samples/auth0-pnp-abc-timesheets/blob/master/timesheets-spa/angular/src/app/auth/auth0-variables.ts.example)** is missing this definition (`silentCallbackURL`).

**Comment by jerriep** [comment]
Thank you for reporting this @adriatic . It is now fixed

**Comment by adriatic** [comment]
Genuinely **my pleasure**. I will continue combing this while sample code and the related article, as I find it really well made.
