### ISSUE TITLE
a couple of typos

### ISSUE THREAD

**Issue by adriatic** [auth0-samples/auth0-pnp-abc-timesheets#9]
Last paragraph in https://auth0.com/docs/architecture-scenarios/application/spa-api/spa-implementation-angular2#2-authorize-the-user

![image](https://user-images.githubusercontent.com/2712405/27618556-0e9710b6-5b8b-11e7-9de2-2b436666961c.png)

**Comment by jerriep** [comment]
@adriatic I have created a PR to fix this.

In future, please create issues related to the actual documentation in the https://github.com/auth0/docs repository

**Comment by jerriep** [comment]
Or even better, you can really help us by just fixing it yourself quickly ;)

![image](https://user-images.githubusercontent.com/1006420/27619857-94c63464-5bef-11e7-8610-6ce4c09b2c0e.png)

**Comment by adriatic** [comment]
@jerriep - I will indeed to as you **[suggest above](https://github.com/auth0-samples/auth0-pnp-abc-timesheets/issues/9#issuecomment-311549392)**
